### ISSUE TITLE
Linking behavior change with libcn as compared to libc066

### ISSUE THREAD

**Issue by Greggk** [bitwiseworks/libc#37]
I switched from libc066 to libcn to build gbm.dll. The build failed trying to link the dll. It failed with a bunch of undefined symbol errors. The problem was that I now needed to explicitly link to stdc++ which was not required using libc066.

**Comment by SilvanScherrer** [comment]
which exe do you use? gcc or g++? could you show the makefile?

**Comment by dmik** [comment]
@Greggk the reason is that Knut's builds of LIBC incldue stdc++ exports from GCC3 (because a GCC DLL with C++ symbols was simply missing back then). It was removed in our builds because: a) our LIBC is built with GCC4 and b) it's simply wrong (C runtime != C++ runtime), especially given that we provide STDCPP6.DLL that contains all C++ symbols.

So in your case, it seems that you launch gcc in such a way that prevents it from dragging stdc++.a by default. Only g++.exe does that (gcc.exe does not) so Silvan's guess may be the right one.

**Comment by Greggk** [comment]
Yes gbm.dll is being compiled with gcc. The problem is caused because it is linking to libraw which is built with g++. I now understand why it worked before and why it doesn't now. I pretty much agree that the new behavior is probably the correct one. I will attach the makefile if you would still like to see it.

**Comment by dmik** [comment]
Not really necessary. Closing this.
