### ISSUE TITLE
clock_gettime()

### ISSUE THREAD

**Issue by SilvanScherrer** [bitwiseworks/libc#53]
clock_gettime() is defined in time.h, but we lack the real function. this is also mentioned as @todo in time.h

**Comment by SilvanScherrer** [comment]
a possible solution is this:

``
int clock_gettime(clockid_t id, struct timespec *ts)
{
    struct timeval tv;

    gettimeofday (&tv, NULL);
    ts->tv_sec = tv.tv_sec;
    ts->tv_nsec = tv.tv_usec * 1000;

    return 0;
}
``

**Comment by dmik** [comment]
Note that it's often used to get the tick count (like in GN's `tick.cc`, see https://github.com/bitwiseworks/qtwebengine-os2/issues/3). And for that it's better to use a high resolution timer

**Comment by SilvanScherrer** [comment]
As long as it gets into libc i dont fight about the better solution. High res time might be better yes.

**Comment by dmik** [comment]
Ok, I sorted it all out. We are lucky here. LIBC already has `gethrtime` (SUN/HP-ism) which returns a snapshot of a high resolution timer (via `DosTmrQueryTime`). This call does `__libc_Back_timeHighResNano` which is an "internal" LIBC worker. This value is a perfect candidate for `clock_gettime(CLOCK_MONOTONIC)`. For `CLOCK_REALTIME` we will use `gettimeofday` indeed as OS/2 doesn't provide a more precise real time clock anyway.

For completeness, I will also do `clock_settime` (will only support CLOCK_REALTIME and call `settimeofday`) and `clock_getres` which returns timer resolution for respective modes.

What I'm not sure about is which resolution we should return. The actual resolution of `gettimeofday` (which internally uses QSV_MS_COUNT) is 31 ms, according to David Azarewics (see https://mantis.arcanoae.com/view.php?id=1702). However, the datatype has a precision of 1 ms and this is the granularity you will see in actual QSV_MS_COUNT snapshots (due to rounding errors and such). The same is true for `DosTmrQueryTime` It's actual resolution is returned by `DosTmrQueryFreq` but the actual granularity of returned snapshots is 1 ns.

**Comment by dmik** [comment]
POSIX and Linux docs for `clock_getres` state only one requirement to the returned value (res): if the time argument of `clock_settime` is not a multiple of res, it will be truncated to a multiple of res. From this POV, we should return 1 ms for CLOCK_REALTIME and 1 ns for CLOCK_MONOTONIC. So this is what I will do.
