### ISSUE TITLE
strndup() strnlen()

### ISSUE THREAD

**Issue by SilvanScherrer** [bitwiseworks/libc#57]
the above 2 functions (possible more strn... functions) are only defined if __USE_GNU is defined. This was probably because long ago GNU invented those functions. But nowadays it's in POSIX standard. Since 2008 or such.

**Comment by dmik** [comment]
__USE_GNU is a LIBC internal define. The public one is _GNU_SOURCE. Here is some background on what it is for: https://stackoverflow.com/questions/5582211/what-does-define-gnu-source-imply.

The reason it's not necessary for `strndup` on other platforms is because it's part of POSIX since 2008. See Linux [man](https://linux.die.net/man/3/strndup) and POSIX [docs](https://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html).

Since LIBC headers haven't been reviewed for POSIX compliance since long, we have such breaks from time to time and fix them as we find them. I guess we will do the same this time as well.

A good place for inspiration is FreeBSD sources (which our LIBC derives a lot from already). The relevant header in this case is this one: https://github.com/freebsd/freebsd/blob/master/include/string.h.
