### ISSUE TITLE
emxomfld: Problems with response files when run from posix shell

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/libc#72]
As stated in https://github.com/bitwiseworks/gcc-os2/issues/22#issuecomment-613466258:
> Some testing shows that the problem might be in LIBC spawn code. Even this simple case: 
```
emxomfld @D:/Temp/aaa
```
> with the contents of `aaa` being just `--help` fails with:
```
emxomfld: _abspath failed on '@D:/Temp/aa.'!!!
```
> but only if run from an .sh script (by sh.exe which uses spawn to start processes). If I use cmd instead, the problem disappears. kLIBC is known to do custom command line processing when both the parent and the child are kLIBC processes (not a wise decision to my taste, I've seen too many problems because of that already). And this is where handling of response files breaks for some reason. More debugging is needed but no time for that right now.

This needs an investigation.

**Comment by dmik** [comment]
BTW, as discussed in #14, it might make sense to use libiberty's response files in all EMX tools (and completely disable kLIBC response file processing). This should fix the problem too.

**Comment by dryeo** [comment]
I tried experimenting by setting MAKESHELL to ksh.exe and cmd.exe and 
make failed the same way.
It still seems the problem is that GCC passes an empty or non-existant 
response file to emxomfld as removing the response file and running the 
emxomfld command line succeeds in producing an xul.dll

**Comment by dmik** [comment]
Make and its MAKESHELL is not involved here at all. It's `gcc.exe` that calls LIBC `spawn("emxomfld")` in your case (and `dash.exe` in my case). Both `gcc.exe` and `dash.exe` as well as `emxomfld.exe` are LIBC processes so special and obscure command line handling (which I expect to be guilty here) occurs.

**Comment by dmik** [comment]
I've stuck deeply with this issue so far because I can't even rebuild gcc now (which I need to do some testing). This command:
```
g++  -Zstack 8192 -Zhigh-mem  -g -march=pentium4  -DIN_GCC     -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -g -Zomf -Zmap -Zargs-wild -Zhigh-mem -o Tcollect2.exe \
        collect2.o collect2-aix.o tlink.o vec.o ggc-none.o collect-utils.o file-find.o hash-table.o selftest.o libcommon.a ../libcpp/libcpp.a -lintl  ../libbacktrace/.libs/backtrace.a ../libiberty/libiberty.a ../libdecnumber/libdecnumber.a
```
produces `Tcollect.map` but no `Tcollect.exe`.

I don't have even a vague idea on why it is happening here.

**Comment by dmik** [comment]
I see now that the Watcom Linker simply crashes:
```
06-16-2020  23:01:33  SYS3175  PID 12c7  TID 0001  Slot 0091
C:\USR\BIN\WL.EXE
c0000005
0003f509
P1=00000001  P2=00000010  P3=XXXXXXXX  P4=XXXXXXXX
EAX=0008738c  EBX=0008734c  ECX=00000000  EDX=0008735c
ESI=00000000  EDI=00087344
DS=0053  DSACC=d0f3  DSLIM=bfffffff
ES=0053  ESACC=d0f3  ESLIM=bfffffff
FS=150b  FSACC=00f3  FSLIM=00000030
GS=0000  GSACC=****  GSLIM=********
CS:EIP=005b:0003f509  CSACC=d0df  CSLIM=bfffffff
SS:ESP=0053:0008732c  SSACC=d0f3  SSLIM=bfffffff
EBP=00000060  FLG=00010297

WL.EXE 0002:0001f509
```

**Comment by StevenLevine** [comment]
It's trapping in GetFrameAddr at:

obj2supp.c:256
    case FIX_FRAME_SEG:
        *addr = frame->u.sdata->u.leader->seg_addr;
        addr->off += frame->u.sdata->a.delta;
        break;

Because frame->u.sdata->u.leader is NULL

P2=00000010 because the offset to seg_addr in the structure is 0x10.

At the moment, this looks more like a problem with the content of an
object or library file rather than a simple out of memory issue.

Debugging this is going to require the wl command line and all the object
files and libraries passed to wl from emxomfld.

Steven

-- 
----------------------------------------------------------------------
"Steven Levine" <steve53@earthlink.net>  Warp/DIY/BlueLion etc.
www.scoug.com www.arcanoae.com www.warpcave.com
----------------------------------------------------------------------

**Comment by dmik** [comment]
Steven, thanks for the feedback! This is just what I thought. I've already rebuilt object files and now rebuilding libraries it uses. I'm pretty sure it's some broken object or library (broken due to TRAP 0008 in the middle of the file write operation). It just takes time... I will report once I get something.

**Comment by StevenLevine** [comment]
One more thing.  The trap has something to do with relocation entries.

The general call path is:

 PModList(...)
    for( obj = head; obj != NULL; obj = obj->n.next_mod ) {
        PModule( obj );

  PModule(mod_entry *obj)
    CurrMod = obj;
    IterateModRelocs( CurrMod->relocs, CurrMod->sizerelocs, IncExecRelocs
) ->
    
  IncExecRelocs->
    BuildReloc->
      GetFrameAddr (traps)

**Comment by dmik** [comment]
OK, I found the culprit. It's my hack from https://github.com/bitwiseworks/libc/issues/82#issuecomment-638450071 that works around OOM. Sigh... I will have to invest more time in both problems it seems.

**Comment by dmik** [comment]
@StevenLevine can it be a WL problem that blindly assumes that some data is always present while it's actually not? Of course, I'm not sure that disabling that part of code in EMXOMF makes it create a valid OMF but when I checked it looked like that.

**Comment by StevenLevine** [comment]
If an allocationed fail, I would expect wl to trap much sooner.

For example, we have:

objpass1.c:655
static seg_leader *MakeNewLeader( segdata *sdata, class_entry *class,
unsigned_16 info )
/**************************************************************************************/
{
    seg_leader *leader;

    sdata->u.leader = leader = InitLeader( sdata->u.name );
    leader->align = sdata->align;

It turns out it's OK for leader to be NULL in some cases:

objpass1.c:617
    leader = RingLookup( class->segs, CheckClassName, sdata );
    if( leader == NULL ) {
        leader = MakeNewLeader( sdata, class, info );
    } else {
        AddToLeader( leader, sdata );
    }

objpass1.c:356
            if( leader != NULL ) {
                AddToGroup( group, leader );
            }

This makes it more likely that some sort of corruption caused the leader
allocation to be bypassed.

**Comment by dmik** [comment]
Are you speaking about allocation in terms of malloc or some logical struct creation instead? What I mean is should WL just skip the section which is missing/null/incomplete/whatefver?

**Comment by StevenLevine** [comment]
My current assestment is that given where the exception occurred, the
pointer should be pointing to valid data and the data is not optional.  As
to why the pointer is NULL is an open question.  If we were to ignore the
missing data, the validity of the resulting executable is unknown.

The only way to answer this kinds of questions with any certainty is with
a testcase.

**Comment by dmik** [comment]
Ok, I've prepared a simple test for you: http://rpm.netlabs.org/test/wlcrash.zip. Just unpack, run `t.sh` and you should give a WL popup log just like the above. The archive contains the emxomf with a hack that drops local-level debug info.

I will continue with the main subject of this ticket in the meanwhile.

**Comment by StevenLevine** [comment]
Thanks dmik.  The testcase works fine.  That is, it traps the same for me
as it does for you. Using -t -t to retain the wlink response file allows
wlink to be run as wl @wl.rsp which also traps the same way, which is a
good thing.  I need to do a debug build of wl.exe because what we have was
built without local symbols and will let you know more once I spend some
more quality time with wdw.

**Comment by dmik** [comment]
I've found the cause. It's libiberty in gcc, emxomfld and libc are not involved. I will reopen https://github.com/bitwiseworks/gcc-os2/issues/14 in favor of this ticket. Will have it open till I get some feedback from Steven though. (To decide what to do next).

**Comment by StevenLevine** [comment]
If you want, split the wlink issue off to a separate ticket.  The wlink
exception probably has nothing to do with the response file issues you
found.  I accidentally linked with ilink and it did not complain, so for
now I have to conclude the fault is entirely wlink's.

**Comment by dmik** [comment]
Very interesting. I would split it off with pleasure. The problem is that I don't know where the OS/2 flavor of wlink is hosted... Upstream, together with all other platforms? Is there a ticket system?

And JFYU, now I'm in paradox condition. EMXOMF w/o the hack can't convert some extremely big Chromium sources and with it it can't convert some GCC sources... Anyway, not a discussion for this ticket.

**Comment by StevenLevine** [comment]
For now, open the ticket here.  It's as good a place as any since it
impacts your ability to build.

OpenWatcom is hosted at www.openwatcom.org.  The repository is Perforce
and the bug tracker is Bugzilla.  This repo also hosts the 4OS2
repository.

You might run into Jiri Malek's

  https://github.com/open-watcom/open-watcom-v2

This is a fork which I have no involment with.

FWIW, some folks have trouble with the Perforce p4 client for OS/2, but
IMO this is user specific.  This issues are understood, as are the
workarounds.  It is a Perforce defect and in the fullness of time, it will
get resolved.

**Comment by dmik** [comment]
Thanks for the info! I guess I will just stick with #82 for now. So please feel free to report there once you find anything so that I could try it too.
