### ISSUE TITLE
libc-debuginfo is easily confused with libc-debug (different, incompatible packages)

### ISSUE THREAD

**Issue by LewisR** [bitwiseworks/libc#77]
The package description for libc-debuginfo is:

> This package provides debug information for package libc.

however, the package actually contains debug information for libcn (not libc). The libc debug package is libc-debug. The two packages are easily confused.

Suggest:

- Leave libc-debug as-is.
- Obsolete libc-debuginfo for lincn-debug and clarify in the package description that it is for libcn and not libc.

An argument could be made that libcn-debug should also obsolete libc-debug, but that's not the point of this ticket.

**Comment by dmik** [comment]
It's not actually like you say: `libcn` (`libcn0` to be exact) is just the DLL name (renamed due to Knut's requirements), not the package name. The package name is still  `libc`. And -debug is just the old name for HLL debug info which we don't use since very long. The new name is -debuginfo which is used in **ALL** RPMs being released since many years. When I rebranded kLIBC under the LIBCn name, I changed -debug to -debuginfo among other things.

All debuginfo subpackages are autogenerated. And this autogeneration is based on what Fedora does. And Fedora doesn't put any strict dependencies on -debuginfo packages, meaning they can be installed even if the respective binaries are not installed. So you can easily face a conflict if there is some other package that already installed these files. 

We've been thinking on putting strict dependencies on debuginfo packages but it's not a very important thing, so it's postponed. And there is another problem with that: it's not clear what to depend it on. The thing is that -debuginfo contains .dbg symbols for all binaries from all other subpackages. So if you have foo and foo-libs, foo-debuginfo will install .dbg for both. Making it dependent on both is not good as if you only have foo-libs, you will not like foo being dragged by foo-debuginfo. The most correct solution here is to have a separate -debuginfo for every subpackage (i.e. foo-debuginfo, foo-libs-debuginfo) but this is not how things work and doing so requires quite a bit of work. Again, not important for now.

So, not a bug.

See also http://trac.netlabs.org/rpm/ticket/134 and http://trac.netlabs.org/rpm/ticket/284.
